version = 0.1

[staging.deploy]
[staging.deploy.parameters]
stack_name = "staging"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

parameter_overrides = [
  "AppSyncApiKey=",
  "SesFrom=",
  "SesTo="
]